title: The Lord of the Rings Open Source Project
description: The Lord of the Rings Open Source Project brings the iconic first of J.R.R.Tolkien's Lord of the Rings books to your computer screen.
show_downloads: true
theme: jekyll-theme-cayman

plugins:
  - jekyll-sitemap
